spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace